#!/bin/sh


REM="libqt5-qtwebengine pidgin patterns-xfce-xfce_office package-update-indicator opensuse-welcome tumbler  gstreamer-plugins-bad gstreamer-plugins-ugly"

zypper remove -y *tumbler*   *pidgin*   $REM
zypper addlock  $REM



zypper install -y xfce4-session xfce4-appfinder  mousepad  \
     baobab rofi  gitg tig meld  \
   xfce4-fsguard-plugin xfce4-systemload-plugin  xfce4-taskmanager \
   fira-code-fonts terminator rofi  xkill catfish seahorse  \
	libgthread-2_0-0  

# libgthread is needed for Idea