#!/bin/bash

SERVICE_FILE_CONTENT="[Unit]
Description=VM cleanup
Before=shutdown.target graphical.target

[Service]
ExecStart=/usr/local/sbin/vm-cleanup
Type=oneshot
User=root

[Install]
WantedBy=default.target"

# Set the service file path
SERVICE_FILE_PATH="/etc/systemd/system/vm-cleanup.service"

# Echo the service file content to the file
echo "$SERVICE_FILE_CONTENT" | tee "$SERVICE_FILE_PATH" > /dev/null

# Enable and start the service
systemctl enable vm-cleanup.service
systemctl start vm-cleanup.service

echo "Service installed and started successfully."
