#!/bin/sh


REM="vim emacs joe PackageKit "


zypper remove -y vim* *emacs* *packagekit* *PackageKit* *-pip* $REM
zypper addlock  $REM


zypper install -y mc htop git-core  fish starship iftop iotop w3m
