#!/bin/bash

#
#  download Candy Icons theme
#
set -e
trap 'echo "Error occurred in: $BASH_COMMAND"; exit 1' ERR

rm -rf /usr/share/icons/candy-icons-master /usr/share/icons/candy-icons

wget -O- https://github.com/EliverLara/candy-icons/archive/refs/heads/master.tar.gz | tar -xz -C /usr/share/icons/
mv /usr/share/icons/candy-icons-master /usr/share/icons/candy-icons


# workaround for webpage shurtcuts showing browser icon
rm -f usr/share/icons/candy-icons/apps/scalable/brave*
rm -f /usr/share/icons/candy-icons/apps/scalable/chrome*
rm -f /usr/share/icons/candy-icons/apps/scalable/google-chrome*
rm -f /usr/share/icons/candy-icons/apps/scalable/chromium*
rm -f /usr/share/icons/candy-icons/apps/scalable/vivaldi*
