#!/bin/bash

# service that cleans /tmp  folder on every reboot
# needed by podman, if killed it would not start on next boot due to garbage in /tmp


# Create the systemd service file
tee /etc/systemd/system/tmp-clean.service > /dev/null << EOF
[Unit]
Description=Clear /tmp folder on boot
Before=systemd-udev.service

[Service]
User=root
ExecStart=/bin/rm -rf /tmp/*
Restart=no

[Install]
WantedBy=sysinit.target
EOF

# Reload systemd daemon to pick up the new service file
systemctl daemon-reload

# Enable the service to start on boot
systemctl enable tmp-clean.service


