#!/bin/bash

if command -v rpm &> /dev/null; then
	CF="/tmp/chrome.rpm"
	wget -O "$CF" "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
	rpm -ivh "$CF"
	rm $CF -f
elif command -v apt-get &> /dev/null; then
	CF="/tmp/chrome.deb"
	wget -O "$CF" https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	apt install -y "$CF"
	rm $CF -f
else
  echo "Unsupported distribution"
  exit 1
fi

echo "Chrome installed successfully"

ln -s  /usr/bin/google-chrome /usr/local/bin/chrome
