#!/bin/bash

if [ "$1" != "dotfiles" ]; then
  echo "Removes and masks packages I do not like"
  echo "Warning, it overwrites and deletes!!"
  echo "The first parameter must be 'dotfiles'."

  exit 1
fi


# setup-upgrade

apt install -y \
  terminator rofi mousepad dconf-cli \
  xfce4-fsguard-plugin  xfce4-taskmanager \
  links mc htop git curl powertop fish iftop iotop sshpass ncdu nano mosh \
  fonts-jetbrains-mono

apt purge -y \
  snapd tumbler tumbler* \
  xfce4-terminal libwebkit2gtk-*  \
  cups*  printer-driver*   \
  *packagekit* apport* yelp*

apt-mark hold snapd
apt-mark hold tumbler
apt-mark hold yelp
apt-mark hold cups-browsed
apt-mark hold cups


# to see largest packages:
#  dpkg-query -W --showformat='${Installed-Size}\t${Package}\n' | sort -n -r | head -n 20
#

if grep -iq "virtualbox" /sys/class/dmi/id/product_name || grep -iq "virtualbox" /sys/class/dmi/id/bios_vendor; then
  echo "Running on VirtualBox"

# stuff for virtualbox

apt install -y  virtualbox-guest-x11 xserver-xorg-video-vmware \

apt purge -y \
    xterm\
    xfce4-screensaver xscreensaver \                             \
    pulseaudio* gstreamer* bluez* pipewire* pavucontrol          \
    network-manager-gnome                                 \
    xserver-xorg-video-all                                \
    memtest86+ mesa-vulkan-drivers fonts-noto-cjk bind9*  \
    colord* avahi-daemon apparmor  poppler-* \
    mesa-* libavcodec* libcodec*

  # firmware not needed on virtualbox
  rm -rf /usr/lib/firmware
  jan-systemd-tty11-root
  jan-systemd-vm-cleanup
  jan-systemd-disable-wallets
  usermod -aG vboxsf jan
  vm-cleanup
fi

jan-systemd-tty12-menu

jan-install-candy-icons
jan-install-starship


#
# lower case user folders
#
cat << EOF >  /etc/xdg/user-dirs.defaults
DESKTOP_DIR=desk
DOWNLOAD_DIR=down
DOCUMENTS_DIR=doc
TEMPLATES_DIR=doc/templates
PUBLICSHARE_DIR=media/share
MUSIC_DIR=media/music
PICTURES_DIR=media/pic
VIDEOS_DIR=media/video
EOF


#
# disable boot animations, show text at boot
#
simple-file-replace /etc/default/grub "quiet splash" "video=1920x1080"
print "# 1024x768  1280x720    1600x900   2560×1600   2560x1440   3840x2160" >> /etc/default/grub
update-grub
systemctl disable plymouth
jan-console-font

apt autoremove -y
apt clean

#
# Lightdm needs this group for autologin?
#
groupadd -r autologin
useradd -m -G autologin  jan
