#!/bin/bash

T="
# Password login disabled
PasswordAuthentication no
ChallengeResponseAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes
"

echo "$T" |  tee -a /etc/ssh/sshd_config.d/pw-disable.conf > /dev/null

