#!/bin/bash

#
#  download Candy Icons theme
#
set -euo pipefail
trap 'echo >&2 "${BASH_SOURCE[0]}:${BASH_LINENO[0]}: Command \`$BASH_COMMAND\` failed with exit code $?"; exit $?' ERR

rm -rf /usr/share/icons/candy-icons-master

wget  --no-verbose  -O- https://github.com/EliverLara/candy-icons/archive/refs/heads/master.tar.gz | tar -xz -C /usr/share/icons/

rm -rf /usr/share/icons/candy-icons
mv /usr/share/icons/candy-icons-master /usr/share/icons/candy-icons


# workaround for webpage shurtcuts showing browser icon
rm -f /usr/share/icons/candy-icons/apps/scalable/*brave*
rm -f /usr/share/icons/candy-icons/apps/scalable/*chrome*
rm -f /usr/share/icons/candy-icons/apps/scalable/*google-chrome*
rm -f /usr/share/icons/candy-icons/apps/scalable/*chromium*
rm -f /usr/share/icons/candy-icons/apps/scalable/*vivaldi*
