#!/bin/bash

apt-get install -y starship
apt install -y starship
zypper install -y  starship
dnf install -y  starship


if ! command -v starship &> /dev/null; then
  wget -O- https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz | tar -xz -C /usr/local/bin/
fi
