#!/bin/bash

. /etc/os-release

case $ID in
    opensuse-leap|opensuse-tumbleweed)
        rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        zypper addrepo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        zypper ref
        zypper install -y brave-browser
        ;;
    fedora)
        dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
        dnf install brave-browser
        ;;
    ubuntu|debian|mint)
        apt update
        apt install -y apt-transport-https curl gnupg
        curl -fsSL https://brave-browser-apt-release.s3.brave.com/brave-core.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
        apt update
        apt install -y brave-browser
        ;;
    *)
        exit 1
        ;;
esac

ln -s  /usr/bin/brave-browser /usr/local/bin/brave
