#!/bin/bash
# change font size
# also use to double size:
#     setfont -d

zypper install -y terminus-bitmap-fonts
apt install -y fonts-terminus fonts-terminus-otb


tee /etc/default/console-setup > /dev/null << EOF
CHARMAP="UTF-8"
CODESET="guess"
FONTFACE="Terminus"
# 6x12, 8x14, 8x16, 10x18, 10x20, 11x22, 12x24, 14x28 and 16x32
FONTSIZE="10x18"
EOF


systemctl enable console-setup
setupcon
