#!/bin/bash


rm /etc/ssh/ssh_host_*
ssh-keygen -R /etc/ssh/ssh_host_rsa_key

ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""
ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""

