#!/bin/sh

useradd \
    --system \
    --home-dir /home/ollamaui \
    --shell /usr/sbin/nologin \
    --comment "Ollama UI" \
    ollamaui

mkdir /home/ollamaui
mkdir /home/ollamaui/bin
chown ollamaui -R /home/ollamaui
chmod 0700  /home/ollamaui


sudo -u ollamaui pip install --break-system-packages open-webui hf_xet

PORT=45033

SERVICE_FILE_CONTENT="
[Unit]
Description=Ollama WebUI Service
After=network-online.target

[Service]
WorkingDirectory=/home/ollamaui
ExecStart=/home/ollamaui/.local/bin/open-webui serve --port $PORT
User=ollamaui
Group=ollamaui
Restart=always
RestartSec=3
Environment="PATH=/usr/local/bin:/usr/bin:/bin:/home/ollamaui/.local/bin"
Environment="HOME=/home/ollamaui"

[Install]
WantedBy=default.target
"

# Set the service file path
SERVICE_FILE_PATH="/etc/systemd/system/ollamaui.service"

# Echo the service file content to the file
echo "$SERVICE_FILE_CONTENT" | tee "$SERVICE_FILE_PATH" > /dev/null

# Enable and start the service
systemctl enable ollamaui.service
systemctl start ollamaui.service

systemctl status ollamaui.service | grep "Active:"

echo ""
echo ""
echo "Ollama UI: http://127.0.0.1:$PORT/"

