#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# suse
if command -v zypper &> /dev/null; then
  zypper --non-interactive update

# fedora
elif command -v dnf &> /dev/null; then
  dnf -y update

# debian/ubuntu
elif command -v apt-get &> /dev/null; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y
  apt-get autoremove -y
  apt-get clean

else
  echo "Unsupported distribution"
  exit 1
fi

echo "== System updated successfully =="
