#!/bin/sh

rm -rf /usr/share/wallpapers/* /usr/share/backgrounds/* /usr/share/xfce4/backdrops/*
rm  -f /usr/bin/xfce4-display-settings /usr/bin/tumblerd /usr/lib64/tumbler-1/tumblerd

rm -f /cleanup-zeros /home/cleanup-zeroes /home/jan/cleanup-zeroes

rm -rf /lib/firmware/* /usr/lib/firmware/*

rm -rf /usr/share/doc/*

apt clean

# needed for systemd, otherwise it will show as failed
exit 0
